openapi: 3.0.3
info:
    contact:
        name: Speakeasy Support
        url: https://speakeasy-dev.slack.com/join/shared_invite/zt-1cwb3flxz-lS5SyZxAsF_3NOq5xc8Cjw
    description: A club that serves drinks and plays jazz. A Goa and Speakeasy example.
    license:
        name: Apache 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0.html
    termsOfService: https://www.speakeasyapi.dev/docs/terms-of-service
    title: The Speakeasy Club
    version: 1.0.0
    x-speakeasy-retries:
        statusCodes: 408,504
        strategy: backoff
servers:
    - url: http://{machine}:51000
      description: club server hosts the band and order services.
      variables:
        machine:
            default: localhost
paths:
    /openapi.json:
        get:
            tags:
                - band
            summary: Download ./gen/http/openapi.json
            operationId: band#/openapi.json
            responses:
                "200":
                    description: File downloaded
    /play:
        post:
            tags:
                - Music operations
            summary: play band
            description: Choose your jazz style.
            operationId: band#play
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/PlayRequestBody'
                        example:
                            style: Bebop
            responses:
                "204":
                    description: No Content response.
    /tea:
        post:
            tags:
                - Drink operations
            summary: tea order
            description: Order a cup of tea.
            operationId: order#tea
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TeaRequestBody'
                        example:
                            includeMilk: false
                            isGreen: false
                            numberSugars: 375920453996173358
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Omnis nesciunt sit est.
                            example: Est eum.
components:
    schemas:
        PlayRequestBody:
            type: object
            properties:
                style:
                    type: string
                    description: Style of music to play
                    example: Bebop
                    enum:
                        - Bebop
                        - Swing
            example:
                style: Bebop
            required:
                - style
        TeaRequestBody:
            type: object
            properties:
                includeMilk:
                    type: boolean
                    description: Whether to have milk.
                    example: true
                isGreen:
                    type: boolean
                    description: Whether to have green tea instead of normal.
                    example: false
                numberSugars:
                    type: integer
                    description: Number of spoons of sugar.
                    example: 1584355970564842854
                    format: int64
            example:
                includeMilk: false
                isGreen: true
                numberSugars: 2220637116220783806
tags:
    - name: order
      description: A waiter that brings drinks.
    - name: band
      description: A band that plays jazz.
