/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Style of music to play
 */
export enum PlayRequestBodyStyle {
    Bebop = "Bebop",
    Swing = "Swing",
}

export class PlayRequestBody extends SpeakeasyBase {
    /**
     * Style of music to play
     */
    @SpeakeasyMetadata()
    @Expose({ name: "style" })
    style: PlayRequestBodyStyle;
}
