/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class TeaRequestBody extends SpeakeasyBase {
    /**
     * Whether to have milk.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "includeMilk" })
    includeMilk?: boolean;

    /**
     * Whether to have green tea instead of normal.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "isGreen" })
    isGreen?: boolean;

    /**
     * Number of spoons of sugar.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "numberSugars" })
    numberSugars?: number;
}
